### ISSUE TITLE
Doesn't work with x86 Unity

### ISSUE THREAD

**Issue by guycalledfrank** [github-beta/unity-preview#1]
When initializing repository on 5.5.2f1 (x86), I get:

> **Failed to load 'Assets/Editor/GitHub/sfw.dll', expected x86 architecture, but was x64 architecture. You must recompile your plugin for x86 architecture.**
> GitHub.Unity.RepositoryWatcher:Initialize() (at /Users/stanleygoldman/Documents/UnityInternal/src/GitHub.Api/Events/RepositoryWatcher.cs:70)
> GitHub.Unity.RepositoryWatcher:Initialize() (at /Users/stanleygoldman/Documents/UnityInternal/src/GitHub.Api/Events/RepositoryWatcher.cs:69)
> GitHub.Unity.RepositoryManager:Initialize() (at /Users/stanleygoldman/Documents/UnityInternal/src/GitHub.Api/RepositoryManager.cs:178)
> GitHub.Unity.<RestartRepository>c__async0:MoveNext() (at /Users/stanleygoldman/Documents/UnityInternal/src/GitHub.Api/ApplicationManagerBase.cs:97)
> System.Runtime.CompilerServices.AsyncTaskMethodBuilder:Start(<RestartRepository>c__async0&)
> GitHub.Unity.ApplicationManagerBase:RestartRepository()
> GitHub.Unity.ApplicationManager:RestartRepository() (at /Users/stanleygoldman/Documents/UnityInternal/src/UnityExtension/Assets/Editor/GitHub.Unity/ApplicationManager.cs:91)
> GitHub.Unity.<Run>c__AnonStorey0:<>m__4(Task`1) (at /Users/stanleygoldman/Documents/UnityInternal/src/GitHub.Api/RepositoryLocator.cs:83)
> System.Threading.Tasks.ThreadPoolTaskScheduler:TaskExecuteWaitCallback(Object)

I know, it's weird that I even use x86 version today, but it's a long story involving some legacy x86 dlls I was already using, so I can't easily switch to x64 right now.

----
Version of Unity: 5.5.2f1 (x86)
Version of GitHub for Unity: 0.8.0.0
Platform: Win7

**Comment by StanleyGoldman** [comment]
Thanks for the report, I'll be sure to make sure it is in the release notes.
We should be able to support x86.

**Comment by liubjtu** [comment]
Error：Failed to load 'Assets/Editor/GitHub/sfw.dll' with error '找不到指定的模块。
Warning：Serialization depth limit 7 exceeded at 'FileTreeNode.children'. There may be an object composition cycle in one or more of your serialized classes.

Serialization hierarchy:
8: FileTreeNode.children
7: FileTreeNode.children
6: FileTreeNode.children
5: FileTreeNode.children
4: FileTreeNode.children
3: FileTreeNode.children
2: GitHub.Unity::ChangesetTreeView.tree
1: GitHub.Unity::ChangesView.tree
0: GitHub.Unity::Window.changesTab

Also, Login failed！

Version of Unity: 5.4.4f1 (x86)
Version of GitHub for Unity: 0.8.0.0
Platform: Win10 X64

**Comment by StanleyGoldman** [comment]
Resolved in v0.10-alpha
