### ISSUE TITLE
utf-8 and cp1251 issue. Russian language in commit messages

### ISSUE THREAD

**Issue by dobrMAN** [github-beta/unity-preview#10]
Sorry, my english is very bad.
There is 2 screen shots with issue.

https://files.gitter.im/ru-sharp/general/B8Wx/thumb/111.png
https://files.gitter.im/ru-sharp/general/z6jF/thumb/222.png

In GitHub it look good, but in Unity Editor i see unreadeble text in commits with russian characters in messages (commits names).

Unity 5.6.0
Windows 10 x64

**Comment by StanleyGoldman** [comment]
Hi @dobrMAN, don't worry I'm happy to help 😃 👍.
I will try to test it out and get back to you.

![](https://files.gitter.im/ru-sharp/general/B8Wx/111.PNG)

![](https://files.gitter.im/ru-sharp/general/z6jF/222.PNG)

**Comment by StanleyGoldman** [comment]
I'm also able to reproduce this on a mac.

Mac OSX Sierra
Unity 5.5.2 x64

![image](https://cloud.githubusercontent.com/assets/417571/25389784/845a7dce-299f-11e7-8616-bb3a81664364.png)

**Comment by dobrMAN** [comment]
@StanleyGoldman, it some different i think. Becouse you don't have russian fonts installed in your system. In my case i just need converting text from UTF-8 to System locale encoding (cp1251 in my case) before show text in History.

**Comment by StanleyGoldman** [comment]
I'm able to build an ultra simple reproduction of the problem.

https://github.com/StanleyGoldman/RussianLanguageOutput

Here we have a simple Process calling a batch file which calls `echo "Я люблю github"` (i love github).
I can obtain a similar result.

![image](https://cloud.githubusercontent.com/assets/417571/25399729/5287ee8e-29be-11e7-8aaf-c744a5f204ed.png)

**Comment by StanleyGoldman** [comment]
Resolved in v0.10-alpha
