### ISSUE TITLE
There is no way to revert files changes

### ISSUE THREAD

**Issue by breineng** [github-beta/unity-preview#12]
There is no way to revert files changes

**Comment by StanleyGoldman** [comment]
You are definitely right about that.
We plan to give you a context menu in the changes tree that will let you revert, but this next build is going to have some bug fixes instead.
I will let you know when that function is coming down the pike.

**Comment by StanleyGoldman** [comment]
Hey @Temka193 there is a new repo and issue for this.
https://github.com/github-for-unity/Unity/issues/14
There is even a PR in progress.
