### ISSUE TITLE
ArgumentException: The value for 'remote' must not be empty

### ISSUE THREAD

**Issue by jeremyPLR** [github-beta/unity-preview#13]
Imported the github-unity package, setup a new project with all default settings.  After saving the remote URL and then trying to push, I received this error:

ArgumentException: The value for 'remote' must not be empty

I went back and checked the Settings tab, and the remote URL string was still there.  After playing and stopping the scene, I tried again and was able to Push and get the push progress bar dialog.  But this operation hung forever and I had to force kill unity.  (I think this is Issue #5)

[github-unity.log.zip](https://github.com/github-beta/unity-preview/files/940902/github-unity.log.zip)

Version of Unity: 5.5.2f1
Version of GitHub for Unity (see console output): 0.8.0.0
Platform (eg. Windows, macOS, Linux): MacOS 10.11.6

**Comment by StanleyGoldman** [comment]
Hey @jeremyPLR thanks for testing and sending in a bug report.
So you are hitting two bugs here..
One is you have to restart after setting the remote for it to be properly realized (i got that fix coming)
The other is this hang people are experiencing, which I'm still diagnosing.

We should have a release soon.

**Comment by shana** [comment]
Fixed in 0.9.1-alpha

The hanging is being tracked in #5, a fix will be on the next release!
