### ISSUE TITLE
Selecting Github->Authenticate results in Null Reference Error if you have not Signed In. 

### ISSUE THREAD

**Issue by kinifi** [github-beta/unity-preview#16]
Version: 5.6.0f3
Github For Windows Version: v0.9.1-alpha
Platform: Windows 10

Steps to Reproduce: 
1. Download the Unity Package File
2. Import->Custom Asset
3. Select Github->Authenticate
4. Observe the Following Error: 

NullReferenceException: Object reference not set to an instance of an object
GitHub.Unity.AuthenticationWindow.OnGUI () (at /Users/shana/code/work/github/UnityInternal/src/UnityExtension/Assets/Editor/GitHub.Unity/UI/AuthenticationWindow.cs:32)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)

[Editor.zip](https://github.com/github-beta/unity-preview/files/948561/Editor.zip)

**Comment by StanleyGoldman** [comment]
Thanks for testing and the bug reports @kinifi

**Comment by StanleyGoldman** [comment]
Hey @kinifi this issue should be resolved by the latest release. Give it a shot and let us know.
