### ISSUE TITLE
Selecting Window->Github results in a History Window Error

### ISSUE THREAD

**Issue by kinifi** [github-beta/unity-preview#17]
Version: 5.6.0f3
Github For Windows Version: v0.9.1-alpha
Platform : Windows 10

Steps to Reproduce:
1. After a fresh install from the Unity Package, select Window->Github
2. Observe the following error: 

NullReferenceException: Object reference not set to an instance of an object
GitHub.Unity.HistoryView.Initialize (IView parent) (at /Users/shana/code/work/github/UnityInternal/src/UnityExtension/Assets/Editor/GitHub.Unity/UI/HistoryView.cs:72)
GitHub.Unity.Window.Setup (IRepository repository) (at /Users/shana/code/work/github/UnityInternal/src/UnityExtension/Assets/Editor/GitHub.Unity/UI/Window.cs:91)
GitHub.Unity.Window.ShowWindow () (at /Users/shana/code/work/github/UnityInternal/src/UnityExtension/Assets/Editor/GitHub.Unity/UI/Window.cs:57)
GitHub.Unity.Window.Window_GitHub () (at /Users/shana/code/work/github/UnityInternal/src/UnityExtension/Assets/Editor/GitHub.Unity/UI/Window.cs:38)

**Comment by CaliberMengsk** [comment]
I get the same. Haven't used the plugin before today.

**Comment by StanleyGoldman** [comment]
Thanks guys, we will let you know when we have more info.

**Comment by StanleyGoldman** [comment]
Resolved in v0.10-alpha
