### ISSUE TITLE
NullReferenceException HistoryView.Initialize

### ISSUE THREAD

**Issue by sjhowie** [github-beta/unity-preview#20]
Started a new project, added the unity github package, clicked on Window -> Github, and received a NullReferenceException in HistoryView.Initialize line 72.

Windows 10, Unity 5.6.0f3 64bit

Not much in the log 

_02:02:10 AM WARN [ 2] <GitInstaller>                      Archive "PlatformResources\windows\git-lfs.zip" missing
02:03:19 AM INFO [ 1]                                     Initializing GitHub for Unity version 0.9.1.0
02:03:25 AM INFO [ 1]                                     Initializing GitHub for Unity version 0.9.1.0
02:15:03 AM INFO [ 1]                                     Initializing GitHub for Unity version 0.9.1.0
02:15:08 AM INFO [ 1]                                     Initializing GitHub for Unity version 0.9.1.0_

but see image below

![image](https://cloud.githubusercontent.com/assets/389444/25311286/d5d46876-27ca-11e7-8747-3cde0b8e1e9a.png)

**Comment by StanleyGoldman** [comment]
Hey @sjhowie thanks for the bug report.
We are tracking this issue in #17
