### ISSUE TITLE
If a pull is required before a push, push is silently failing

### ISSUE THREAD

**Issue by shana** [github-beta/unity-preview#21]
Version: 0.9.1-alpha

Push isn't reporting if a pull is required before the push, and silently exits with no information.

**Comment by thorade** [comment]
Also happens with v0.11-alpha

The unity-preview readme clearly told me to NOT add a readme or license when creating the repo:
https://github.com/github-beta/unity-preview#publish-a-new-repository
But if you DO add a readme, this is exactly what will happen (push fails silently, pull fails with message "unrelated history").

**Comment by StanleyGoldman** [comment]
There is a new issue for this: https://github.com/github-for-unity/Unity/issues/54
