### ISSUE TITLE
Exceptions thrown from Dispose methods in ApplicationManager and RepositoryWatcher

### ISSUE THREAD

**Issue by shana** [github-beta/unity-preview#22]
Version of Unity (eg. 5.5.0f1): 5.5
Version of GitHub for Unity (see console output): 0.9.1-alpha
Platform (eg. Windows, macOS, Linux): Windows

Occasionally, `Dispose()` in ApplicationManager and RepositoryWatcher throw exceptions when Unity reloads the domain for compilation or play mode. RepositoryWatcher seems to happen more often, ApplicationManager is rarer (only twice in a full day of working in Unity)

The exception getting thrown from ApplicationManager seems to cause Unity to crash.

**Comment by StanleyGoldman** [comment]
Resolved in v0.10-alpha
