### ISSUE TITLE
Dedicated Git console for outputting commands and output

### ISSUE THREAD

**Issue by shana** [github-beta/unity-preview#23]
Having a dedicated console window for showing the git commands being executed and the output of those commands would be very useful, both for educational purposes and for debugging.

**Comment by thorade** [comment]
[GitExtensions](https://github.com/gitextensions/) uses [ConEmu](https://github.com/Maximus5/ConEmu)  for this (at least on Windows)

**Comment by StanleyGoldman** [comment]
There is a new issue for this
