### ISSUE TITLE
Unable to switch branches in editor

### ISSUE THREAD

**Issue by infinstarlight** [github-beta/unity-preview#25]
Version of Unity (eg. 5.5.0f1): 5.6.0f3
Version of GitHub for Unity (see console output): 0.0.9.1
Platform (eg. Windows, macOS, Linux): Windows

What happened

In the editor, the plugin defaults to the master branch. I'm doing majority of my work in a separate 'prototyping' branch before creating a pull request into the master. However, I cannot switch to the prototyping branch, all I get is a blank window pop-up and all it says is OK.

![github error](https://cloud.githubusercontent.com/assets/3934211/25315244/41b2ca56-2820-11e7-9536-c94db41e700e.PNG)

[(pj)github-unity.zip](https://github.com/github-beta/unity-preview/files/949833/pj.github-unity.zip)

**Comment by StanleyGoldman** [comment]
Hey @professionaljones thanks for testing and the bug report.
I will let you know when I have more details for this one.

**Comment by StanleyGoldman** [comment]
Hey @professionaljones would you mind trying that test again, but before you do, there is a checkbox on the Settings tab to enable trace logging. Could you make sure that's enabled before you try your test.
Thanks.

**Comment by infinstarlight** [comment]
Apologies for the delay, haven't experienced the issue on macOS but I haven't tried again on Windows, will update when something changes.

**Comment by StanleyGoldman** [comment]
Hey @professionaljones I'm trying my best to reproduce the issue against the latest release and I'm not having much luck. Can you give it another shot for me?

**Comment by StanleyGoldman** [comment]
Hey @professionaljones we pushed out a new build, this one has another bug fix in the "create branch" area. Give it a shot and let me know how it goes.

I'm going to close out this issue since we haven't been able to reproduce it since.
