### ISSUE TITLE
Unable to login with Github Enterprise Account

### ISSUE THREAD

**Issue by knsh14** [github-beta/unity-preview#26]
Version of Unity: 5.4.2p2
Version of GitHub for Unity: v0.9.1-alpha
Platform: macOS

I can't choose Github Enterprise URL and login Enterprise account on Authenticate View.
Please make a dropdown menu to choose Github.com or Enterprise to login.

**Comment by shana** [comment]
Thank you for the report! This is definitely high on our list of things to fix, the UI is not quite finished yet. :+1:

**Comment by StanleyGoldman** [comment]
There is a new repo and a new issue for this project.

https://github.com/github-for-unity/Unity/issues/2
