### ISSUE TITLE
Unable to Authenticate before fixing script error

### ISSUE THREAD

**Issue by infinstarlight** [github-beta/unity-preview#3]
Version of Unity (eg. 5.5.0f1): 5.6.0f3
Version of GitHub for Unity (see console output): 0.8.0.0
Platform (eg. Windows, macOS, Linux): macOS

What happened

I was unable to find the settings and GitHub options in the Editor before fixing an error in an unrelated script. Not sure if this affects me since I have initialized this repo outside of Unity, but this may cause problems for others.

**Comment by StephenHodgson** [comment]
Usually menu items do not appear unless the editor can compile.  Try removing the offending script and re-import the extension.

**Comment by infinstarlight** [comment]
Already done and the GitHub options appeared. Thank you!

**Comment by infinstarlight** [comment]
Also, since I'm using GitHub Desktop and the Unity plugin, should I use both or one or the other?

**Comment by StanleyGoldman** [comment]
@StephenHodgson is correct about that. Thanks.
@professionaljones you can definitely enjoy using both of them together.
