### ISSUE TITLE
InvalidOperationException: Unable to reflect EditorApplication.editorApplicationQuit

### ISSUE THREAD

**Issue by brainydexter** [github-beta/unity-preview#32]
Version of Unity (eg. 5.5.0f1): 5.3.5f1
Version of GitHub for Unity (see console output): 0.9.1.0
Platform (eg. Windows, macOS, Linux): macOS

What happened
I did a fresh install of github for unity and I got the above error (with backtrace):

InvalidOperationException: Unable to reflect EditorApplication.editorApplicationQuit
GitHub.Unity.ApplicationManager.SecureQuitActionField () (at /Users/shana/code/work/github/UnityInternal/src/UnityExtension/Assets/Editor/GitHub.Unity/ApplicationManager.cs:133)
GitHub.Unity.ApplicationManager.get_EditorApplicationQuit () (at /Users/shana/code/work/github/UnityInternal/src/UnityExtension/Assets/Editor/GitHub.Unity/ApplicationManager.cs:115)
GitHub.Unity.ApplicationManager.ListenToUnityExit () (at /Users/shana/code/work/github/UnityInternal/src/UnityExtension/Assets/Editor/GitHub.Unity/ApplicationManager.cs:102)
GitHub.Unity.ApplicationManager..ctor (IMainThreadSynchronizationContext synchronizationContext) (at /Users/shana/code/work/github/UnityInternal/src/UnityExtension/Assets/Editor/GitHub.Unity/ApplicationManager.cs:36)
GitHub.Unity.EntryPoint.get_ApplicationManager () (at /Users/shana/code/work/github/UnityInternal/src/UnityExtension/Assets/Editor/GitHub.Unity/EntryPoint.cs:89)
GitHub.Unity.EntryPoint.Initialize () (at /Users/shana/code/work/github/UnityInternal/src/UnityExtension/Assets/Editor/GitHub.Unity/EntryPoint.cs:60)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at /Users/builduser/buildslave/unity/build/artifacts/generated/common/editor/EditorApplicationBindings.gen.cs:217)

>> On macOS, the extension log file is at `~/.local/share/GitHubUnityDebug/github-unity.log`
That path did not exist for me.

I don't have a /Users/shana directory. I think one of the devs forgot to take out the hardcoded path from the code.

**Comment by StanleyGoldman** [comment]
Hey @brainydexter thanks for the bug report.

This bug is happening because we don't yet support Unity 5.3.
I was just working on this the other day, I'll let you know when we have it fixed.

**Comment by shana** [comment]
> I don't have a /Users/shana directory. I think one of the devs forgot to take out the hardcoded path from the code.

Assuming this refers to the paths in the stacktrace, don't worry about that, that's the path recorded in the symbols when things got compiled, it doesn't refer to things on your machine.

PS: oof fat fingers, accidentally closed this :-P

**Comment by StanleyGoldman** [comment]
Hey @brainydexter! There is a new repo and a new issue to track this item.
https://github.com/github-for-unity/Unity/issues/1
There is even a PR in progress!
