### ISSUE TITLE
Commit with GitHub Desktop causes Unity crash

### ISSUE THREAD

**Issue by yvan-sraka** [github-beta/unity-preview#36]
[%LOCALAPPDATA%\GitHubUnityDebug\github-unity.log](https://github.com/github-beta/unity-preview/files/967016/github-unity.log.txt)

Version of Unity: **5.6.0f3**
Version of GitHub for Unity: **0.8-alpha**
Platform: **Windows 10 x64 Creator Update**

When I commit with GitHub Desktop, Unity freeze, CPU usage goes to 0%, no commands will respond to the user, so I have to kill the `Unity.exe` process using the Windows Task Manager and restart the Unity Editor.

Thank you for your help!

**Comment by shana** [comment]
@yvan-sraka Could you try with the [latest release](https://github.com/github-beta/unity-preview/releases/tag/v0.10-alpha) (0.10-alpha) to see if this still happens? You should delete the `GitHub` folder inside `Assets/Editor` before importing the new one, otherwise it will complain that a native library is locked and can't update.

**Comment by yvan-sraka** [comment]
I think this issue is a duplicate of https://github.com/github-beta/unity-preview/issues/5: I can not reproduce it right now, but I remember that it seems to me it is rather the  GitHub Desktop's **Sync** action (so `git pull -r; git push`), than commits, which causes Unity to crash ...

**Comment by StanleyGoldman** [comment]
Hey @yvan-sraka the bug your originally reported sounded different to me (it was actually a bit interesting).

**Comment by yvan-sraka** [comment]
I no longer have the problem with the new, Electron based, [Github Desktop Beta](https://desktop.github.com/)!

**Comment by StanleyGoldman** [comment]
Nice. Glad it's working out.
