### ISSUE TITLE
Support file diffs

### ISSUE THREAD

**Issue by bjennings76** [github-beta/unity-preview#39]
Feature Request: Add the ability to quickly show change diffs through the UI. Often this is done using 'Ctrl-D' or double-clicking a changed file.

**Comment by StanleyGoldman** [comment]
Hey @bjennings76 thanks for testing and thanks for the feedback. Agreed, we definitely need diff support.

**Comment by StanleyGoldman** [comment]
Hey @bjennings76! There is a new repo and a new issue for this.
https://github.com/github-for-unity/Unity/issues/55

Hopefully we can get this fixed soon.
