### ISSUE TITLE
LFS Lock Failed - Could not find file

### ISSUE THREAD

**Issue by schutztj** [github-beta/unity-preview#4]
![image](https://cloud.githubusercontent.com/assets/1100754/24872270/b1950180-1dd1-11e7-8cbf-877a431421a3.png)

[GitHubUnityLogs.zip](https://github.com/github-beta/unity-preview/files/910804/GitHubUnityLogs.zip)

Version of Unity (eg. 5.5.0f1): 5.6.0b11 x64
Version of GitHub for Unity (see console output): Latest alpha
Platform (eg. Windows, macOS, Linux): Windows

What happened:
Attempted to lock a file via the context menu in Unity and it fails saying it cannot find the file.  It appears that it assumes the Unity project is the root of the GIT repository (ie. /Assets is in the root repository folder) instead of using the actual path to the file in the repo.

Failed path: HXT.LockTest\Assets\Scenes\Main.unity
Actual path: HXT.LockTest\Unity\TestProject\Assets\Scenes\Main.unity

**Comment by shana** [comment]
Thanks for the testing and for the report! We'll get a fix for this 🐛 in on our next alpha.😊

**Comment by shana** [comment]
Fixed in 0.9.1-alpha
