### ISSUE TITLE
Authentication fails even first time

### ISSUE THREAD

**Issue by Claytonious** [github-beta/unity-preview#41]
Unity 5.6.0p3
Github for Unity v0.10-alpha (downloaded from releases tab)
Platform:Mac OS X (10.12.4)

![image](https://cloud.githubusercontent.com/assets/601503/25821919/b8cb2ad0-33eb-11e7-9b80-023f53d147f2.png)

**Comment by shana** [comment]
Looks like you might not have git on your path? We're not packaging a git and git lfs on the mac, so you'll need to install the latest versions (especially git lfs) to get things working. The easiest way of doing this is via homebrew.

We're about to release 0.11, which includes a bunch of authentication fixes, so if you fix git and you still have problems, you can try the next alpha (out in an hour or so)

**Comment by StanleyGoldman** [comment]
Hey @Claytonious we pushed that release out. Give it a shot.

**Comment by thorade** [comment]
@Claytonious Your username is `Claytonious` but in the screenshot you are using your email address. 
Does it work if you use correct credentials?

**Comment by StanleyGoldman** [comment]
Good catch @thorade

**Comment by StanleyGoldman** [comment]
Hey @Claytonious did you try again with your username instead of your email?

**Comment by Claytonious** [comment]
Yes, I did, and with the latest release (0.11-alpha), with slightly improved results (it now gets to 2 factor auth and I did receive the auth code), but then ultimately the same error:

![image](https://user-images.githubusercontent.com/601503/27386699-7316b02c-564b-11e7-93d3-4f97a63ecb75.png)

**Comment by Claytonious** [comment]
![image](https://user-images.githubusercontent.com/601503/27386760-a239adaa-564b-11e7-8233-78583b41d2f7.png)

**Comment by thorade** [comment]
After solving #47 I am now at the same stage, login fails, even when logging in for the very first time.
Using the v0.11-alpha package on Unity 5.6.1f1

![bildschirmfoto 2017-06-23 um 09 51 49](https://user-images.githubusercontent.com/314571/27471931-cd1cebea-57f9-11e7-8946-7584adddb281.png)

Also, there are problems with the back button: When clicking back, the authentication code is in the username field, and after correcting that and clicking verify again, the username is in the authentication code field.

**Comment by shana** [comment]
We're working on tracking this one down. In the meantime, if you go into settings tab and set the path to git in there, does that help?

**Comment by thorade** [comment]
Yes, that helps. I can now successfully login to github, with 2FA.

**Comment by shana** [comment]
@thorade Thanks for the test, this is very helpful!

**Comment by StanleyGoldman** [comment]
Hey @thorade there is a new repo with a new build. It should fix some of the bugs you saw.
Give it a shot when you can.

https://github.com/github-for-unity/Unity
