### ISSUE TITLE
Add a staging area for commits similar to how SourceTree's GUI does it.

### ISSUE THREAD

**Issue by absurdhart** [github-beta/unity-preview#45]
![2017-06-14 14_14_19-sourcetree](https://user-images.githubusercontent.com/25354924/27155049-20c341c6-510c-11e7-8514-a13065ac234d.png)

This would make the organization of including and excluding files in commits very clear to the users.

**Comment by StanleyGoldman** [comment]
Hey @absurdhart thanks for testing and for the feedback. Sorry to leave you hanging for a bit there.
I'm going to mark this as a feature idea and we can haggle over it after we hit version 1. 😃 

Out of curiousity, what don't you like about checkbox treeview?

**Comment by absurdhart** [comment]
@StanleyGoldman With regards to checkboxes only, they are ok for smaller projects but can get unwieldy when many assets are involved. It is very easy to make a mistake and accidentally commit a deleted, added, or changed file that you did not intend to commit.

For me, a great GIT Source Control GUI should try to warn and prevent as many mistakes as possible with relation to check-in. Staging is another step to confirm the user is actually committing what they want. I think that is one of the biggest benefits of using SourceTree over Unity's Collaborate.

Also, I don't think it should replace your checkbox treeview. The checkbox treeview is perfectly fine and a nice feature. I think the "Staging Window" should be an additional step on top of that. 

So when someone clicks the checkbox to add/edit/delete a file, then that file should move into the "Staging Window". And if they uncheck the file in the "Staging Window" the file should move back outside the "Staging Window". When they have the file changes they want to commit in the staging area, then the Commit button should become active.

**Comment by StanleyGoldman** [comment]
Hey @absurdhart! There is a new repo and a new issue for this item.
https://github.com/github-for-unity/Unity/issues/52

There is also a new build, check it out.
