### ISSUE TITLE
Switching layouts forces me to re-initialize git

### ISSUE THREAD

**Issue by connordodge** [github-beta/unity-preview#46]
[github-unity.log.zip](https://github.com/github-beta/unity-preview/files/1076167/github-unity.log.zip)

[changing layouts forces me to reinitialize git mov.zip](https://github.com/github-beta/unity-preview/files/1076168/changing.layouts.forces.me.to.reinitialize.git.mov.zip)

What happened

Whenever I switch my editor layout to a different pre-configured layout I have to reinitialize git.

**Comment by StanleyGoldman** [comment]
Hey @cdodge89, sorry to leave you hanging on a response there.
Thanks for testing. We are working hard to get to beta and the next build.
Please hang in there.

Thanks for the bug report. I have a feeling i know the cause of the bug (I think it's fixed already for the next release).

**Comment by connordodge** [comment]
Awesome. It's shaping up to be a great tool!

**Comment by StanleyGoldman** [comment]
Hey @cdodge89 There is a new repo and a new issue for this.
https://github.com/github-for-unity/Unity/issues/53

Hopefully we can get it resolved soon.
