### ISSUE TITLE
Installation on a Mac

### ISSUE THREAD

**Issue by thorade** [github-beta/unity-preview#47]
Version of Unity: 5.5 something and 5.6.1f1
Version of GitHub for Unity (see console output): v0.11-alpha
Platform: macOS Sierra

What happened: Installation failed
On three different Macs, I tried to install the package by downloading and double clicking, as stated in the installation instructions. Unity opens, but the github tab/window just is not there. No error message, and I cannot find the log.
Any ideas/comments? Has anybody installed it successfully on a Mac?

**Comment by StanleyGoldman** [comment]
Hey @thorade sorry to leave you waiting for a response and thanks for testing.
We've been working really hard towards beta and a new build is coming.
Please hang in there for a little bit longer.

Regarding your bug, something is going wrong in the startup of the application.
Can you check for your Unity editor log?
It should be at: `~/Library/Logs/Unity/Editor.log`

**Comment by thorade** [comment]
Thanks, found the log now, not sure why I could not find it before...
[Editor_log.txt](https://github.com/github-beta/unity-preview/files/1091237/Editor_log.txt)

**Comment by StanleyGoldman** [comment]
This is a log after you reproduced the error right?
That log file gets deleted and restarted every time you start up Unity.

**Comment by thorade** [comment]
Sorry, might have been another version. Here is a fresh log.
[Editor_log.txt](https://github.com/github-beta/unity-preview/files/1091345/Editor_log.txt)

**Comment by thorade** [comment]
And yet another log, this time I stopped at the Unity screen where I can choose the project I want to open (the other logs are after opening a project, to see whether the github pane is there or not).

[Editor_log.txt](https://github.com/github-beta/unity-preview/files/1091414/Editor_log.txt)

**Comment by shana** [comment]
@thorade Could you try creating a new project in Unity, and then double clicking on the extension package on the Mac Finder? Unity should show an import dialog with a list of files, clicking on Import should install the extension in the new project.

**Comment by thorade** [comment]
Yes, then it works! Thanks.
So Unity just has to be open when double-clicking on the package.
On Windows this was not necessary, only on macOS.

**Comment by StanleyGoldman** [comment]
woot!
