### ISSUE TITLE
Changes hang Unity 2017.1.0b1

### ISSUE THREAD

**Issue by amigax** [github-beta/unity-preview#49]
Please fill out the data below and include a zip with the Unity log file and the extension log file.
On Windows, the extension log file is at `%LOCALAPPDATA%\GitHubUnityDebug\github-unity.log`
On macOS, the extension log file is at `~/.local/share/GitHubUnityDebug/github-unity.log`

If you prefer not to submit your log files through the issue tracker, send them
to unity@github.com with the issue number.

Version of Unity (eg. 5.5.0f1): 2017.1.0b1
Version of GitHub for Unity (see console output):
Platform (eg. Windows, macOS, Linux): Win10

What happened

I added a cube to see if changes would show, this hangs unity enitrely, sticks at 12% cpu but does nothing at all. Requires the process to be killed.  I dont think this happpened before I installed this.

**Comment by StanleyGoldman** [comment]
Thanks again @amiga. I will have more information for you soon.

**Comment by amigax** [comment]
thanks @StanleyGoldman  also it doesnt explain how you "add" all your existing files to github?  Surely it needs to take all your files to upload?

**Comment by StanleyGoldman** [comment]
In the version that you have it is a little bit manual at the moment. You have to create a repository on github.com yourself and add it to the repo in Settings. Then you will be able to push and pull.

Soon we will have a proper publish dialog.

**Comment by StanleyGoldman** [comment]
Hey @amiga! There is a new repo and a new issue for this.
Hopefully we can work it out soon.

https://github.com/github-for-unity/Unity/issues/51
