### ISSUE TITLE
Name and E-Mail doesn't get saved on Windows

### ISSUE THREAD

**Issue by Rinma** [github-beta/unity-preview#9]
Version of Unity (eg. 5.5.0f1): 5.6.0f3
Version of GitHub for Unity (see console output): 0.8.0.0
Platform (eg. Windows, macOS, Linux): Windows 10

What happened
I tried to enter a name and email for the commit messages in the git configuration fields. The name and email field were filled and when i changed the values and clicked save they didn't get saved, even worse they get removed completely. Now i don't have any values in this fields.

Edit:
When i change the name and email in a terminal and restart Unity the values i tried to enter before the restart of unity appeared again (the values who didn't get saved in the first way). Also when i hit save in unity and check in the terminal the value of `user.name` didn't changed.

[github-unity.log.txt](https://github.com/github-beta/unity-preview/files/923828/github-unity.log.txt)

**Comment by StanleyGoldman** [comment]
Hi @Rinma thanks for testing and sending us this bug report.

Can I ask you to do another test for me?
Before you do, there is a checkbox on the Settings tab. "Enable Trace Logging"
Hit that checkbox and try your test again.

<img src="https://cloud.githubusercontent.com/assets/417571/25066587/0a626058-21f8-11e7-9f27-092a25dac231.png" height=250/>

The logs should have something a bit more useful that way.

**Comment by Rinma** [comment]
[github-unity.log.txt](https://github.com/github-beta/unity-preview/files/923890/github-unity.log.txt)

**Comment by StanleyGoldman** [comment]
Thanks @Rinma I'll let you know when I have more questions for you

**Comment by StanleyGoldman** [comment]
Hey @Rinma when you did that test again, did it actually work?
I'm looking at the log and the message returned seems to indicate success.

**Comment by Rinma** [comment]
I tested this on the same day i opened the issue.
Today i tested it with version 0.10.0.0 and i added a .gitconfig file, removed the git repository and created it again because it is written in known issues. 
Now i have a strange behavior. 
It kinda works but why does it set the username and email for global and not local and why will the .gitconfig not updated? 
Also i see the updated config values in the windows cmd but not in the ubuntu bash and after i set the configs with a terminal it stops working with the unity plugin.
[github-unity.log.txt](https://github.com/github-beta/unity-preview/files/966885/github-unity.log.txt)

**Comment by StanleyGoldman** [comment]
Hey @Rinma there is a new repo and a new build.
https://github.com/github-for-unity/Unity

Pleas test again and let us know if you have any troubles.
